project:
  type: website
  output-dir: docs

website:
  title: "Yanin's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://ygalvan05.github.io/yg_rcc_blog/
      - icon: linkedin
        href: https://www.linkedin.com/in/yanin-galvan-735890336/
format:
  html:
    theme: pulse
    css: styles.css

editor: visual

